import '../styles/globals.css';
import { Analytics } from "@vercel/analytics/next"
import { ClerkProvider } from '@clerk/nextjs';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider dynamic>
    <html lang="en">
      <Analytics/>
      <body>{children}</body>
    </html>
    </ClerkProvider>
  )
}
